backend:
  host: http://localhost
  port: 8000
  checks:
    lint: true
    format: true
    type_check: true
    test: true
  coverage_threshold: 100

frontend:
  port: 3000
  checks:
    lint: true
    type_check: true
    test: true
  coverage_threshold: 80
